name: incidentapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  provider: ^6.0.5
  http: ^1.0.0
  jwt_decoder: ^2.0.1
  connectivity_plus: ^6.1.1
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  intl: ^0.18.0 
  sqflite: ^2.0.0+4
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

dependency_overrides:
  async: ^2.12.0
  characters: ^1.4.0
  collection: ^1.19.1
  js: ^0.7.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  boolean_selector: ^2.1.2
  clock: ^1.1.2
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  test_api: ^0.7.4
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
